version: '3.8'
services:
  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    env_file: ./.env
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - myPersonalNet
  app:
    build: 
      context: ./packages/cryptography/
    restart: unless-stopped
    env_file: ./.env
    ports:
      - '5000:5000'
    environment:
      - DB_HOST=mysqldb
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    networks:
      - myPersonalNet
    depends_on:
      - mysqldb
  websocket:
    build: 
      context: ./packages/websocket/
    restart: unless-stopped
    env_file: ./.env
    ports:
      - '5001:5001'
    environment:
      - DB_HOST=mysqldb
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    networks:
      - myPersonalNet
    depends_on:
      - mysqldb
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: mysqldb
    ports:
      - "8080:80"
    networks:
      - myPersonalNet
  apacheserver:
    build: 
      context: ./packages/cryptography/apache-config
    ports:
      - "80:80"
    volumes:
      - ./packages/cryptography/apache/apacheconf:/usr/local/apache2/conf/sites
    networks:
      - myPersonalNet
networks:
  myPersonalNet:
    driver: bridge
    
volumes: 

  db:
    name: app-data
   